# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/2003UJAN/Dynamic-Surge-Pricing-Optimization-Ride-hailing-Mobility/blob/main/generate_data.ipynb
"""

import pandas as pd
import numpy as np

np.random.seed(42)
num_samples = 1000

data = {
    "hour": np.random.randint(0, 24, num_samples),
    "traffic": np.random.randint(1, 10, num_samples),
    "weather": np.random.randint(1, 4, num_samples),
    "events": np.random.randint(0, 2, num_samples),
    "distance_km": np.random.uniform(2, 30, num_samples),
    "demand": np.random.randint(50, 500, num_samples)
}

df = pd.DataFrame(data)
df.to_csv("synthetic_rides.csv", index=False)
print("Synthetic dataset created: synthetic_rides.csv")